### PR TITLE
Target API 25, fix issue #46, use OkHttp for all http calls

### LINKED ISSUE #46: Compilation instructions
To compile Shortyz I needed to remove the `androidkeyinfo.properties` and `signingConfigs` parts of `app/build.gradle`.  Could we modify these to make it easier for other contributors to work on Shortyz?  This would enable other services like Travis continuous integration.

The README.md should also include any other setup such as:

```
echo sdk.dir=/path/to/android-sdk-linux/ > local.properties
JAVA_HOME=/path/to/jdk-7 ./gradlew clean assembleDebug
```

### PR DESCRIPTION
**Pull request by paulirwin**
Resolves #46 allowing for the community to easily pull, build, and run the app in Android Studio.

This also updates the target API version and dependencies to use API 25 for Android 7.1 Nougat. This allows for split-screen use of the app. 

The largest breaking change in going from API 22 to 23+ was the permissions model. You now have to request permissions at the time that you use them. Due to the complex code in BrowseActivity, my changes here were not as clean as I normally would have preferred but they seem to get the job done. I haven't fully tested all of the corner cases of what happens if a user denies the storage permission, but if they do that, they should just re-launch the app and it will prompt again. If anyone has any suggestions here on how to make this code more robust I'm happy to improve this PR.

Another pretty straightforward change was to use NotificationCompat.Builder instead of the deprecated Notification constructor. This was necessitated by the API change to remove the deprecated Notification.setLatestEventInfo method.

The calls to Apache HttpClient were causing warnings, and OkHttp which was already in the project supports Android 2.3 and later (as does this app), so I went ahead and got rid of those warnings by making all requests use OkHttpClient.

Because of that change, JellyBeanUtil was no longer necessary, and I determined that DefaultUtil was in a broken state (due to returning null from onActionBarCustom) so I changed DefaultUtil to be abstract and made its no-op methods abstract as well. The code in these classes can certainly be improved further, but I didn't want to waste a lot of time on it if Gingerbread wasn't going to be supported much longer. It and Honeycomb together have less than 1.5% of the market today, and it would certainly clean up a good amount of code to support only 4.0.3 and later (API 15). If you'd like me to make the change to drop support for API 9-14, I'd be happy to add that to this PR or submit another.

Thanks for your work on this app so far. This is a great app, I am using it every day, and I'm happy to contribute back. Thanks for your consideration!

### CODE REVIEW

**Comment by kebernet** [comment]
Thanks! I will take a look at it this weekend. Shortyz has been a little idle because I have been working on another personal project lately.

 I am a little concerned about the GB issues. The PlayStore version still has a pretty significant install base on GB. I will take a look and see if I can clean that up.

Also, yeah, getting rid of the last bits of Apache HTTP has been on the TODOs for an eon at this point.

**Comment by paulirwin** [comment]
@kebernet Sounds good, and thanks. One thing that's bugging me is that firstrun/NYTimes.java:69 shows a warning in Android Studio about needing to do the Android 6+ permission check, as GET_ACCOUNTS is listed as a [dangerous permission](https://developer.android.com/guide/topics/security/permissions.html#perm-groups), but the app seems to work just fine without a check around it. Maybe it's just not returning any accounts without the permission request? I'll do some more digging.

**Comment by paulirwin** [comment]
Found it [here](https://developer.android.com/reference/android/accounts/AccountManager.html#getAccounts()):

> Clients of this method that have not been granted the GET_ACCOUNTS permission, will only see those accounts managed by AbstractAccountAuthenticators whose signature matches the client.

So it's not returning any accounts but the call still succeeds without the permission. I personally don't think showing a pre-populated list of emails in the one-time login box is worth asking the user for permission to access their account info, but if you think this is important I can add the permission check/callback.

**Comment by kebernet** [comment]
It is weird they did that, honestly. The pre-populated email address pattern was a recommended UI thing a couple years ago. :P 

I am kind of tempted to put the permission check on focus of the username box. 70+% of the users aren't going to fill in the NYT credentials anyway. However about 80% of the emails I get are about people fat-fingering their NYT creds, so I kind of want to make it as idiot proof as possible.

**Comment by paulirwin** [comment]
That's a good idea. I can update this PR to include that if you'd like.

**Pull request merged**
