### PR TITLE
Use the GPU for gameplay

### PR DESCRIPTION
**Pull request by rossmeissl**

### CODE REVIEW

**Comment by kebernet** [comment]
So, I need to see if there is some way to split the difference here. The problem with enabling GPU rendering is it causes problems on Android <= 4.1 with rendering on a lot of devices.

Do you have any stack information on the crash you were seeing.

**Comment by andrewgaul** [comment]
@rossmeissl What benefit does GPU rendering provide?  shortyz only has a simple grid.

**Comment by rossmeissl** [comment]
@andrewgaul without that setting Shortyz crashed 100% of the time after typing the first letter

**Comment by andrewgaul** [comment]
@rossmeissl Using the GPU usually *introduces* crashes; enabling it here likely masks some other issue.  Can you get a stack trace?

**Comment by rossmeissl** [comment]
@andrewgaul I can no longer reproduce — this must have been fixed in an Android update sometime since January.

**Pull request closed without merging**
